---

- name: Change user shell to zsh
  user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Locales
  block:
    - name: Adding locales in /etc/default/libc-locales
      lineinfile:
        path: /etc/default/libc-locales
        regexp: "#{{ item }}"
        line: "{{ item }}" 
      with_items: "{{ locale }}"

    - name: force-reconfigure the glibc-locales package
      command: "xbps-reconfigure -fa"

- name: Delete .bash files in home directory
  file:
    path: "/home/{{ username }}/{{ item }}"
    state: absent
  with_items:
    - ".bashrc"
    - ".bash_logout"
    - ".bash_profile"

- name: Enabling services for sway
  block:
    - name: Enable dbus
      service: 
        name: dbus
        enabled: yes
    
    - name: Enable polkit
      service: 
        name: polkitd
        enabled: yes

- name: Pipewire setup
  block:
    - name: Create pipewire.conf.d
      ansible.builtin.file:
        path: /etc/pipewire/pipewire.conf.d
        state: directory
        mode: '0755'
    - name: Copy 10-wireplumber.conf
      ansible.builtin.file:
        src: /usr/share/examples/wireplumber/10-wireplumber.conf
        dest: /etc/pipewire/pipewire.conf.d/
        state: link
    - name: Copy 20-pipewire-pulse.conf
      ansible.builtin.file:
        src: /usr/share/examples/pipewire/20-pipewire-pulse.conf
        dest: /etc/pipewire/pipewire.conf.d/
        state: link
