---

- name: Change user shell to zsh
  user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Locales
  block:
    - name: Adding locales in /etc/default/libc-locales
      lineinfile:
        path: /etc/default/libc-locales
        regexp: "#{{ item }}"
        line: "{{ item }}" 
      with_items: "{{ locale }}"

    - name: force-reconfigure the glibc-locales package
      command: "xbps-reconfigure -fa"

- name: Delete .bash files in home directory
  file:
    path: "/home/{{ username }}/{{ item }}"
    state: absent
  with_items:
    - ".bashrc"
    - ".bash_logout"
    - ".bash_profile"

- name: Enabling services for sway
  block:
    - name: Enable dbus
      service: 
        name: dbus
        enabled: yes
    
    - name: Enable polkit
      service: 
        name: polkitd
        enabled: yes

- name: Pipewire setup
  block:
    - name: Create pipewire.conf.d
      ansible.builtin.file:
        path: /etc/pipewire/pipewire.conf.d
        state: directory
        mode: '0755'
    - name: Copy 10-wireplumber.conf
      ansible.builtin.file:
        src: /usr/share/examples/wireplumber/10-wireplumber.conf
        dest: /etc/pipewire/pipewire.conf.d/10-wireplumber.conf
        state: link
    - name: Copy 20-pipewire-pulse.conf
      ansible.builtin.file:
        src: /usr/share/examples/pipewire/20-pipewire-pulse.conf
        dest: /etc/pipewire/pipewire.conf.d/20-pipewire-pulse.conf
        state: link

- name: Fixing FN keys bug on Thinkpad E14 g2
  block:
    - name: Enable crond
      service: 
        name: crond
        enabled: yes

    - name: Adding task for crond
      ansible.builtin.cron:
        name: "a job for reboot"
        special_time: reboot
        job: "sudo rtcwake -m mem -s 1"


- name: Setting up an Internet connection
  vars:
    iwdtext: |
      [General]
      EnableNetworkConfiguration=true
  block:
    - name: Enable iwd
      service: 
        name: iwd
        enabled: yes
    - name: EnableNetworkConfiguration=true in /etc/iwd/main.conf
      copy:
        content: "{{ iwdtext }}"
        dest: /etc/iwd/main.conf
        force: no

- name: Bluetooth
  block:
    - name: Enable bluetoothd
      service:
        name: bluetoothd
        enabled: yes

    - name: Add user to a group bluetoothd
      user:
        name: "{{ username }}"
        groups: "bluetooth"
        append: yes

- name: Enable Power Saving - tlp
  service:
    name: tlp
    enabled: yes


